services:
  app:
    image: todo-front-nginx
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
    ports:
      - 3001:3000
    container_name: todo-front-nginx
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
  server:
    image: express-server
    ports:
      - 3000:3000
    container_name: express-server
    environment:
      - REDIS_URL=//redis-dev:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo-dev:27017/the_database
    volumes:
      - ./todo-backend:/usr/src/app
  redis:
    image: redis
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']
    container_name: redis-dev
    volumes:
      - ./todo-backend/redis_data:/data
  mongo:
    image: mongo
    ports:
      - 3456:27017
    container_name: mongo-dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db
    